targets:
  $default:
    builders:
      injectable_generator:injectable_builder:
        generate_for:
          - lib/core/dependency_injection/di.dart
          - lib/core/dependency_injection/core_module.dart
          - lib/features/**/data/repositories_impl/**.dart
          - lib/features/**/data/datasources/**.dart
          - lib/features/**/domain/usecases/**.dart
          - lib/features/**/presentation/bloc/**.dart
          - lib/features/**/bloc/**.dart
          - lib/services/real_time/**.dart
          - lib/services/localization/localization_service.dart
          - lib/services/paste/paste_capture_service.dart
          - lib/data/**/datasources/**.dart
          - lib/data/**/repositories_impl/**.dart
          - lib/data/**/dao/**.dart
          - lib/domain/**/usecases/**.dart
      json_serializable:
        generate_for:
          - lib/features/**/data/dto/**.dart
          - lib/features/**/data/api/**.dart
          - lib/data/**/api/**.dart
          - lib/data/**/dto/**.dart
          - lib/data/**/dto/**/**.dart
      drift_dev:
        generate_for:
          - lib/data/database/app_database.dart
          - lib/data/**/tables/**.dart
          - lib/data/**/dao/**.dart
      retrofit_generator:
        generate_for:
          - lib/data/**/api/**.dart
          - lib/features/**/data/api/**.dart