targets:
  $default:
    builders:
      injectable:
        generate_for:
          - lib/core/dependency_injection/di.dart
          - lib/features/**/data/repositories_impl/**.dart
          - lib/features/**/domain/usecases/**.dart
          - lib/data/**/datasources/**.dart
          - lib/data/**/repositories_impl/**.dart
          - lib/services/real_time/**.dart
      json_serializable:
        generate_for:
          - lib/features/**/data/dto/**.dart
          - lib/features/**/data/api/**.dart
          - lib/data/**/api/**.dart
          - lib/data/**/dto/**.dart
          - lib/data/**/dto/**/**.dart
#      drift_dev:
#        generate_for:
#          - lib/data/database/app_database.dart
#          - lib/data/**/tables/**.dart