// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD85htVrnKAF6m0Onu1hhqo0zLj4V9XqVM',
    appId: '1:84165506338:web:40c11e03699fdc4134a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    authDomain: 'genesis-workspace.firebaseapp.com',
    storageBucket: 'genesis-workspace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5drputG5jJGXIZWA7TCmWqex0l-Ukv38',
    appId: '1:84165506338:android:45560afaf52f494434a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    storageBucket: 'genesis-workspace.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7vhg-golKIN7IFw8OBxHOkpokwHbLiPU',
    appId: '1:84165506338:ios:97cffac2af954ce934a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    storageBucket: 'genesis-workspace.firebasestorage.app',
    iosBundleId: 'com.example.genesisWorkspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7vhg-golKIN7IFw8OBxHOkpokwHbLiPU',
    appId: '1:84165506338:ios:97cffac2af954ce934a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    storageBucket: 'genesis-workspace.firebasestorage.app',
    iosBundleId: 'com.example.genesisWorkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD85htVrnKAF6m0Onu1hhqo0zLj4V9XqVM',
    appId: '1:84165506338:web:f304f4e2a2e3378834a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    authDomain: 'genesis-workspace.firebaseapp.com',
    storageBucket: 'genesis-workspace.firebasestorage.app',
  );
}
