// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:genesis_workspace/core/config/constants.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD85htVrnKAF6m0Onu1hhqo0zLj4V9XqVM',
    appId: '1:84165506338:web:40c11e03699fdc4134a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    authDomain: 'genesis-workspace.firebaseapp.com',
    storageBucket: 'genesis-workspace.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0E2PkBUUVYbx0JWXT_ATFBrKXxoeMMDg',
    appId: '1:313579879000:android:f8556564ea20fe8be3e82d',
    messagingSenderId: '313579879000',
    projectId: 'genesis-workspace-59e6a',
    storageBucket: 'genesis-workspace-59e6a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA36Aw99xw1Aaht3Lk34kMmiBT_3mimyvE',
    appId: '1:313579879000:ios:ceb1a4b0833dbc90e3e82d',
    messagingSenderId: '313579879000',
    projectId: 'genesis-workspace-59e6a',
    storageBucket: 'genesis-workspace-59e6a.firebasestorage.app',
    iosBundleId: 'genesis.workspace',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7vhg-golKIN7IFw8OBxHOkpokwHbLiPU',
    appId: '1:84165506338:ios:97cffac2af954ce934a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    storageBucket: 'genesis-workspace.firebasestorage.app',
    iosBundleId: 'com.example.genesisWorkspace',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD85htVrnKAF6m0Onu1hhqo0zLj4V9XqVM',
    appId: '1:84165506338:web:f304f4e2a2e3378834a17b',
    messagingSenderId: '84165506338',
    projectId: 'genesis-workspace',
    authDomain: 'genesis-workspace.firebaseapp.com',
    storageBucket: 'genesis-workspace.firebasestorage.app',
  );
}