import 'package:flutter/material.dart';
import 'package:genesis_workspace/core/models/emoji.dart';
import 'package:shared_preferences/shared_preferences.dart';

class AppConstants {
  static const String legacyPath = String.fromEnvironment('legacy_ui');
  static const String firebaseApiKey = String.fromEnvironment('firebase_api_key');
  static const String lkUrl = String.fromEnvironment('lk_url');

  static const String appName = 'genesis_workspace';

  static const String tusVersion = '1.0.0';

  static const int jobTitleProfileDataIndex = 1;
  static const int bossNameProfileDataIndex = 2;

  static const String mailCalendarUuid = "00000000-0000-0000-0000-000000000001";

  static late String baseUrl;
  static int? selectedOrganizationId;

  static const String versionConfigUrl = 'https://repository.genesis-core.tech/genesis_workspace/workspace-index.json';
  static const String versionConfigShaUrl =
      'https://repository.genesis-core.tech/genesis_workspace/workspace-index.json.sha256';

  static final popularEmojis = [
    UnicodeEmojiDisplay(emojiName: ":thumbs_up:", emojiUnicode: "1F44D"),
    UnicodeEmojiDisplay(emojiName: ":heart:", emojiUnicode: "2764"),
    UnicodeEmojiDisplay(emojiName: ":joy:", emojiUnicode: "1F602"),
    UnicodeEmojiDisplay(emojiName: ":open_mouth:", emojiUnicode: "1F62E"),
    UnicodeEmojiDisplay(emojiName: ":cry:", emojiUnicode: "1F622"),
    UnicodeEmojiDisplay(emojiName: ":clap:", emojiUnicode: "1F44F"),
  ];

  static Future<void> init() async {
    final SharedPreferences prefs = await SharedPreferences.getInstance();

    final String? savedBaseUrl = prefs.getString(SharedPrefsKeys.baseUrl);
    final int? savedOrganizationId = prefs.getInt(SharedPrefsKeys.selectedOrganizationId);

    if (savedBaseUrl != null && savedBaseUrl.trim().isNotEmpty) {
      baseUrl = savedBaseUrl.trim();
    } else {
      baseUrl = '';
    }
    selectedOrganizationId = savedOrganizationId;
  }

  static setBaseUrl(String url) {
    baseUrl = url;
  }

  static void setSelectedOrganizationId(int? id) {
    selectedOrganizationId = id;
  }

  static const List<String> kImageExtensions = [
    'png',
    'jpg',
    'jpeg',
    'gif',
    'webp',
    'bmp',
    'heic',
    'heif',
    'svg',
  ];

  static const List<Color> folderColors = <Color>[
    Color(0xFF2563EB),
    Color(0xFF4F46E5),
    Color(0xFF0D9488),
    Color(0xFF059669),
    Color(0xFFF59E0B),
    Color(0xFFDC2626),
    Color(0xFF6B7280),
    Color(0xFF334155),
  ];

  static const Set<String> mediaKitSupportedFormats = {
    '3dostr',
    '4xm',
    'aa',
    'aac',
    'aax',
    'ac3',
    'ace',
    'acm',
    'act',
    'adf',
    'adp',
    'ads',
    'adx',
    'aea',
    'afc',
    'aiff',
    'aix',
    'alaw',
    'alias_pix',
    'alp',
    'amr',
    'amrnb',
    'amrwb',
    'anm',
    'apac',
    'apc',
    'ape',
    'apm',
    'apng',
    'aptx',
    'aptx_hd',
    'aqtitle',
    'argo_asf',
    'argo_brp',
    'argo_cvg',
    'asf',
    'asf_o',
    'ass',
    'ast',
    'au',
    'av1',
    'avi',
    'avr',
    'avs',
    'avs2',
    'avs3',
    'bethsoftvid',
    'bfi',
    'bfstm',
    'bin',
    'bink',
    'binka',
    'bit',
    'bitpacked',
    'bmp_pipe',
    'bmv',
    'boa',
    'bonk',
    'brender_pix',
    'brstm',
    'c93',
    'caf',
    'cavsvideo',
    'cdg',
    'cdxl',
    'cine',
    'codec2',
    'codec2raw',
    'concat',
    'cri_pipe',
    'dash',
    'data',
    'daud',
    'dcstr',
    'dds_pipe',
    'derf',
    'dfa',
    'dfpwm',
    'dhav',
    'dirac',
    'dnxhd',
    'dpx_pipe',
    'dsf',
    'dshow',
    'dsicin',
    'dss',
    'dts',
    'dtshd',
    'dv',
    'dvbsub',
    'dvbtxt',
    'dxa',
    'ea',
    'ea_cdata',
    'eac3',
    'epaf',
    'exr_pipe',
    'f32be',
    'f32le',
    'f64be',
    'f64le',
    'ffmetadata',
    'film_cpk',
    'filmstrip',
    'fits',
    'flac',
    'flic',
    'flv',
    'frm',
    'fsb',
    'fwse',
    'g722',
    'g723_1',
    'g726',
    'g726le',
    'g729',
    'gdigrab',
    'gdv',
    'gem_pipe',
    'genh',
    'gif',
    'gif_pipe',
    'gsm',
    'gxf',
    'h261',
    'h263',
    'h264',
    'hca',
    'hcom',
    'hdr_pipe',
    'hevc',
    'hls',
    'hnm',
    'ico',
    'idcin',
    'idf',
    'iff',
    'ifv',
    'ilbc',
    'image2',
    'image2pipe',
    'imf',
    'ingenient',
    'ipmovie',
    'ipu',
    'ircam',
    'iss',
    'iv8',
    'ivf',
    'ivr',
    'j2k_pipe',
    'jacosub',
    'jpeg_pipe',
    'jpegls_pipe',
    'jpegxl_pipe',
    'jv',
    'kux',
    'kvag',
    'laf',
    'lavfi',
    'live_flv',
    'lmlm4',
    'loas',
    'lrc',
    'luodat',
    'lvf',
    'lxf',
    'm4v',
    'matroska',
    'webm',
    'mca',
    'mcc',
    'mgsts',
    'microdvd',
    'mjpeg',
    'mjpeg_2000',
    'mlp',
    'mlv',
    'mm',
    'mmf',
    'mods',
    'moflex',
    'mov',
    'mp4',
    'm4a',
    '3gp',
    '3g2',
    'mj2',
    'mp3',
    'mpc',
    'mpc8',
    'mpeg',
    'mpegts',
    'mpegtsraw',
    'mpegvideo',
    'mpjpeg',
    'mpl2',
    'mpsub',
    'msf',
    'msnwctcp',
    'msp',
    'mtaf',
    'mtv',
    'mulaw',
    'musx',
    'mv',
    'mvi',
    'mxf',
    'mxg',
    'nc',
    'nistsphere',
    'nsp',
    'nsv',
    'nut',
    'nuv',
    'obu',
    'ogg',
    'oma',
    'paf',
    'pam_pipe',
    'pbm_pipe',
    'pcx_pipe',
    'pfm_pipe',
    'pgm_pipe',
    'pgmyuv_pipe',
    'pgx_pipe',
    'phm_pipe',
    'photocd_pipe',
    'pictor_pipe',
    'pjs',
    'pmp',
    'png_pipe',
    'pp_bnk',
    'ppm_pipe',
    'psd_pipe',
    'psxstr',
    'pva',
    'pvf',
    'qcp',
    'qdraw_pipe',
    'qoi_pipe',
    'r3d',
    'rawvideo',
    'realtext',
    'redspark',
    'rka',
    'rl2',
    'rm',
    'roq',
    'rpl',
    'rsd',
    'rso',
    'rtp',
    'rtsp',
    's16be',
    's16le',
    's24be',
    's24le',
    's32be',
    's32le',
    's337m',
    's8',
    'sami',
    'sap',
    'sbc',
    'sbg',
    'scc',
    'scd',
    'sdns',
    'sdp',
    'sdr2',
    'sds',
    'sdx',
    'ser',
    'sga',
    'sgi_pipe',
    'shn',
    'siff',
    'simbiosis_imx',
    'sln',
    'smjpeg',
    'smk',
    'smush',
    'sol',
    'sox',
    'spdif',
    'srt',
    'stl',
    'subviewer',
    'subviewer1',
    'sunrast_pipe',
    'sup',
    'svag',
    'svg_pipe',
    'svs',
    'swf',
    'tak',
    'tedcaptions',
    'thp',
    'tiertexseq',
    'tiff_pipe',
    'tmv',
    'truehd',
    'tta',
    'tty',
    'txd',
    'ty',
    'u16be',
    'u16le',
    'u24be',
    'u24le',
    'u32be',
    'u32le',
    'u8',
    'v210',
    'v210x',
    'vag',
    'vbn_pipe',
    'vc1',
    'vc1test',
    'vfwcap',
    'vidc',
    'vividas',
    'vivo',
    'vmd',
    'vobsub',
    'voc',
    'vpk',
    'vplayer',
    'vqf',
    'w64',
    'wady',
    'wav',
    'wavarc',
    'wc3movie',
    'webm_dash_manifest',
    'webp_pipe',
    'webvtt',
    'wsaud',
    'wsd',
    'wsvqa',
    'wtv',
    'wv',
    'wve',
    'xa',
    'xbin',
    'xbm_pipe',
    'xmd',
    'xmv',
    'xpm_pipe',
    'xvag',
    'xwd_pipe',
    'xwma',
    'yop',
    'yuv4mpegpipe',
  };
}

class SharedPrefsKeys {
  static const String locale = 'locale';
  static const String isWebAuth = 'isWebAuth';
  static const String selectedOrganizationId = 'selectedOrganizationId';
  static const String baseUrl = 'baseUrl';
  static const String notificationSound = 'notificationSound';
  static const String prioritizePersonalUnread = 'prioritizePersonalUnread';
  static const String prioritizeUnmutedUnreadChannels = 'prioritizeUnmutedUnreadChannels';
  static const String videoAudioHintDismissed = 'videoAudioHintDismissed';
}

class AssetsConstants {
  static const String audioPop = 'audio/pop.wav';
  static const String audioWhoop = 'audio/whoop.wav';
}
